"""create initial tables

Revision ID: da39df1b4c2b
Revises: 
Create Date: 2026-07-27 12:15:43.441092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da39df1b4c2b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('meeting_key', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=50), nullable=False),
    sa.Column('country_name', sa.String(length=100), nullable=False),
    sa.Column('circuit_short_name', sa.String(length=100), nullable=False),
    sa.Column('date_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('date_end', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key')
    )
    op.create_index(op.f('ix_sessions_meeting_key'), 'sessions', ['meeting_key'], unique=False)
    op.create_index(op.f('ix_sessions_year'), 'sessions', ['year'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('team_colour', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_number', name='uq_driver_per_session')
    )
    op.create_table('intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('gap_to_leader', sa.Float(), nullable=True),
    sa.Column('interval', sa.Float(), nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_number', 'recorded_at', name='uq_interval_snapshot')
    )
    op.create_index('ix_intervals_session_driver_time', 'intervals', ['session_id', 'driver_number', 'recorded_at'], unique=False)
    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_duration', sa.Float(), nullable=True),
    sa.Column('date_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_pit_out_lap', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_number', 'lap_number', name='uq_lap_per_driver')
    )
    op.create_table('pit_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('pit_duration', sa.Float(), nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'driver_number', 'recorded_at', name='uq_position_snapshot')
    )
    op.create_index('ix_positions_session_driver_time', 'positions', ['session_id', 'driver_number', 'recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_positions_session_driver_time', table_name='positions')
    op.drop_table('positions')
    op.drop_table('pit_stops')
    op.drop_table('laps')
    op.drop_index('ix_intervals_session_driver_time', table_name='intervals')
    op.drop_table('intervals')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_sessions_year'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_meeting_key'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
